EASY_PROBLEMS = "questions_easy.csv" 
CHALLENGING_PROBLEMS = "questions_challenging.csv"
HARD_PROBLEMS = "questions_hard.csv"

QUESTION_SETS = [EASY_PROBLEMS, CHALLENGING_PROBLEMS, HARD_PROBLEMS]

EASY_LEVEL = 0
CHALLENGING_LEVEL = 1
HARD_LEVEL = 2

QUESTIONS_PER_LEVEL = 3